apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: resumeapp
  name: resumeapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: resumeapp
status:
  loadBalancer: {}
